baseURL = "https://www.vislies.org/2022/"
theme   = "vislies-hugo-theme"
title   = "VisLies"

[Params]
this_year = 2023
first_year = 2015

mainSections = "post"
subtitle     = "A Hugo Theme"

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1