baseURL = "https://www.vislies.org"
theme   = "vislies-hugo-theme"
title   = "VisLies"

[Params]
mainSections = "post"
subtitle     = "A Hugo Theme"

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1